/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import java.text.ParseException;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author victor.hmoreira3
 */
public class DadosCliente extends javax.swing.JFrame {
   
    public DadosCliente() {
        initComponents();
    }
    /**
     * 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sexoidentifier = new javax.swing.ButtonGroup();
        Tela = new javax.swing.JTabbedPane();
        DadosBasicos = new javax.swing.JPanel();
        email = new javax.swing.JTextField();
        avancar = new javax.swing.JButton();
        LabelNome = new javax.swing.JLabel();
        LabelCPF = new javax.swing.JLabel();
        LabelEmail = new javax.swing.JLabel();
        LabelTel = new javax.swing.JLabel();
        Telefone = new javax.swing.JFormattedTextField();
        CPF = new javax.swing.JFormattedTextField();
        Nome = new javax.swing.JFormattedTextField();
        Sexo = new javax.swing.JLabel();
        MasculinoButton = new javax.swing.JRadioButton();
        FemininoButton = new javax.swing.JRadioButton();
        NiButton = new javax.swing.JRadioButton();
        LabelNascimento = new javax.swing.JLabel();
        Data = new javax.swing.JFormattedTextField();
        LabelEstadoCivil = new javax.swing.JLabel();
        EstadoCivil = new javax.swing.JComboBox<>();
        Endereço = new javax.swing.JPanel();
        VoltarButton = new javax.swing.JButton();
        LabelCEP = new javax.swing.JLabel();
        LabelEndereços = new javax.swing.JLabel();
        LabelNumber = new javax.swing.JLabel();
        LabelComp = new javax.swing.JLabel();
        LabelReferencia = new javax.swing.JLabel();
        LabelBairro = new javax.swing.JLabel();
        LabelCidade = new javax.swing.JLabel();
        LabelEstado = new javax.swing.JLabel();
        ConcluirButton = new javax.swing.JButton();
        CEP = new javax.swing.JFormattedTextField();
        Endereco = new javax.swing.JFormattedTextField();
        Numero = new javax.swing.JFormattedTextField();
        Complemento = new javax.swing.JFormattedTextField();
        Referencia = new javax.swing.JFormattedTextField();
        Bairro = new javax.swing.JFormattedTextField();
        Estado = new javax.swing.JFormattedTextField();
        Cidade = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        avancar.setText("Avançar");
        avancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avancarActionPerformed(evt);
            }
        });

        LabelNome.setText("Nome Completo:");

        LabelCPF.setText("CPF:");

        LabelEmail.setText("E-mail:");

        LabelTel.setText("Telefone:");

        try {
            Telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            CPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            Nome.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("********************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeActionPerformed(evt);
            }
        });

        Sexo.setText("Sexo:");

        Sexoidentifier.add(MasculinoButton);
        MasculinoButton.setText("Masculino");

        Sexoidentifier.add(FemininoButton);
        FemininoButton.setText("Feminino");

        Sexoidentifier.add(NiButton);
        NiButton.setText("Não informar");

        LabelNascimento.setText("Data de Nascimento:");

        try {
            Data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        LabelEstadoCivil.setText("Estado Civíl:");

        EstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro", "Casado", "Viúvo", "Divorciado" }));
        EstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoCivilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DadosBasicosLayout = new javax.swing.GroupLayout(DadosBasicos);
        DadosBasicos.setLayout(DadosBasicosLayout);
        DadosBasicosLayout.setHorizontalGroup(
            DadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DadosBasicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DadosBasicosLayout.createSequentialGroup()
                        .addGap(0, 452, Short.MAX_VALUE)
                        .addComponent(avancar))
                    .addGroup(DadosBasicosLayout.createSequentialGroup()
                        .addGroup(DadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DadosBasicosLayout.createSequentialGroup()
                                    .addComponent(LabelCPF)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(CPF))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DadosBasicosLayout.createSequentialGroup()
                                    .addComponent(LabelEmail)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(DadosBasicosLayout.createSequentialGroup()
                                .addComponent(LabelNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DadosBasicosLayout.createSequentialGroup()
                                .addGroup(DadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelTel)
                                    .addComponent(Sexo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(DadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(DadosBasicosLayout.createSequentialGroup()
                                        .addComponent(MasculinoButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(FemininoButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(NiButton))))
                            .addGroup(DadosBasicosLayout.createSequentialGroup()
                                .addComponent(LabelNascimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Data, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DadosBasicosLayout.createSequentialGroup()
                                .addComponent(LabelEstadoCivil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        DadosBasicosLayout.setVerticalGroup(
            DadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DadosBasicosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(DadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNome)
                    .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCPF)
                    .addComponent(CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelEmail))
                .addGap(18, 18, 18)
                .addGroup(DadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTel)
                    .addComponent(Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sexo)
                    .addComponent(MasculinoButton)
                    .addComponent(FemininoButton)
                    .addComponent(NiButton))
                .addGap(18, 18, 18)
                .addGroup(DadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNascimento)
                    .addComponent(Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEstadoCivil)
                    .addComponent(EstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(avancar)
                .addContainerGap())
        );

        Tela.addTab("Dados Básicos", DadosBasicos);

        VoltarButton.setText("Voltar");
        VoltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarButtonActionPerformed(evt);
            }
        });

        LabelCEP.setText("CEP:");

        LabelEndereços.setText("Endereço:");

        LabelNumber.setText("Número:");

        LabelComp.setText("Complemento:");

        LabelReferencia.setText("Informação de referência:");

        LabelBairro.setText("Bairro");

        LabelCidade.setText("Cidade:");

        LabelEstado.setText("Estado:");

        ConcluirButton.setText("Concluir");
        ConcluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConcluirButtonActionPerformed(evt);
            }
        });

        try {
            CEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEPActionPerformed(evt);
            }
        });

        try {
            Numero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            Estado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout EndereçoLayout = new javax.swing.GroupLayout(Endereço);
        Endereço.setLayout(EndereçoLayout);
        EndereçoLayout.setHorizontalGroup(
            EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EndereçoLayout.createSequentialGroup()
                .addComponent(VoltarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ConcluirButton)
                .addContainerGap())
            .addGroup(EndereçoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(EndereçoLayout.createSequentialGroup()
                            .addComponent(LabelCEP)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(CEP, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(EndereçoLayout.createSequentialGroup()
                            .addComponent(LabelEndereços)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Endereco))
                        .addGroup(EndereçoLayout.createSequentialGroup()
                            .addComponent(LabelCidade)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(LabelEstado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(EndereçoLayout.createSequentialGroup()
                            .addComponent(LabelNumber)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(LabelComp)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(EndereçoLayout.createSequentialGroup()
                            .addComponent(LabelReferencia)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Referencia)))
                    .addGroup(EndereçoLayout.createSequentialGroup()
                        .addComponent(LabelBairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 150, Short.MAX_VALUE))
        );
        EndereçoLayout.setVerticalGroup(
            EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EndereçoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCEP)
                    .addComponent(CEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEndereços)
                    .addComponent(Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNumber)
                    .addComponent(Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelComp)
                    .addComponent(Complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelReferencia)
                    .addComponent(Referencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelBairro)
                    .addComponent(Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCidade)
                    .addComponent(LabelEstado)
                    .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                .addGroup(EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VoltarButton)
                    .addComponent(ConcluirButton))
                .addContainerGap())
        );

        Tela.addTab("Endereço", Endereço);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tela, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tela)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void avancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avancarActionPerformed
        this.Tela.setSelectedIndex(1);
    }//GEN-LAST:event_avancarActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void VoltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarButtonActionPerformed
       this.Tela.setSelectedIndex(0);
    }//GEN-LAST:event_VoltarButtonActionPerformed

    private void EstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadoCivilActionPerformed

    private void ConcluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConcluirButtonActionPerformed
        JOptionPane.showMessageDialog(this, "Cadastro Concluido!");
    }//GEN-LAST:event_ConcluirButtonActionPerformed

    private void NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeActionPerformed
      
    }//GEN-LAST:event_NomeActionPerformed

    private void CEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CEPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DadosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DadosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DadosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DadosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DadosCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Bairro;
    private javax.swing.JFormattedTextField CEP;
    private javax.swing.JFormattedTextField CPF;
    private javax.swing.JFormattedTextField Cidade;
    private javax.swing.JFormattedTextField Complemento;
    private javax.swing.JButton ConcluirButton;
    private javax.swing.JPanel DadosBasicos;
    private javax.swing.JFormattedTextField Data;
    private javax.swing.JFormattedTextField Endereco;
    private javax.swing.JPanel Endereço;
    private javax.swing.JFormattedTextField Estado;
    private javax.swing.JComboBox<String> EstadoCivil;
    private javax.swing.JRadioButton FemininoButton;
    private javax.swing.JLabel LabelBairro;
    private javax.swing.JLabel LabelCEP;
    private javax.swing.JLabel LabelCPF;
    private javax.swing.JLabel LabelCidade;
    private javax.swing.JLabel LabelComp;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelEndereços;
    private javax.swing.JLabel LabelEstado;
    private javax.swing.JLabel LabelEstadoCivil;
    private javax.swing.JLabel LabelNascimento;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel LabelNumber;
    private javax.swing.JLabel LabelReferencia;
    private javax.swing.JLabel LabelTel;
    private javax.swing.JRadioButton MasculinoButton;
    private javax.swing.JRadioButton NiButton;
    private javax.swing.JFormattedTextField Nome;
    private javax.swing.JFormattedTextField Numero;
    private javax.swing.JFormattedTextField Referencia;
    private javax.swing.JLabel Sexo;
    private javax.swing.ButtonGroup Sexoidentifier;
    private javax.swing.JTabbedPane Tela;
    private javax.swing.JFormattedTextField Telefone;
    private javax.swing.JButton VoltarButton;
    private javax.swing.JButton avancar;
    private javax.swing.JTextField email;
    // End of variables declaration//GEN-END:variables
}
