/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import java.text.ParseException;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import Model.Cliente;
import Controller.Controller;
import Utils.validadorClientes;
/**
 *
 * @author victor.hmoreira3
 */
public class cadastrarClientes extends javax.swing.JFrame {
   
    public cadastrarClientes() {
        initComponents();
    }
    /**
     * 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SexoID = new javax.swing.ButtonGroup();
        Table = new javax.swing.JTabbedPane();
        DadosBasicos = new javax.swing.JPanel();
        avancar = new javax.swing.JButton();
        JLabelNomeCompleto = new javax.swing.JLabel();
        JLabelCPF = new javax.swing.JLabel();
        JLabelEmail = new javax.swing.JLabel();
        JLabelTelefone = new javax.swing.JLabel();
        JLabelSexo = new javax.swing.JLabel();
        JLabelData = new javax.swing.JLabel();
        JLabelEstadoCivil = new javax.swing.JLabel();
        Nome = new javax.swing.JFormattedTextField();
        CPF = new javax.swing.JFormattedTextField();
        Email = new javax.swing.JFormattedTextField();
        Telefone = new javax.swing.JFormattedTextField();
        Masculino = new javax.swing.JRadioButton();
        Feminino = new javax.swing.JRadioButton();
        NaoInformar = new javax.swing.JRadioButton();
        Data = new javax.swing.JFormattedTextField();
        EstadoCivil = new javax.swing.JComboBox<>();
        Endereço = new javax.swing.JPanel();
        Concluir = new javax.swing.JButton();
        JLabelCEP = new javax.swing.JLabel();
        JLabelEnderecos = new javax.swing.JLabel();
        JLabelNumero = new javax.swing.JLabel();
        JLabelComplemento = new javax.swing.JLabel();
        JLabelBairro = new javax.swing.JLabel();
        JLabelCidade = new javax.swing.JLabel();
        JLabelEstado = new javax.swing.JLabel();
        Cep = new javax.swing.JFormattedTextField();
        Endereco = new javax.swing.JFormattedTextField();
        Numero = new javax.swing.JFormattedTextField();
        Complemento = new javax.swing.JFormattedTextField();
        Bairro = new javax.swing.JFormattedTextField();
        Estado = new javax.swing.JFormattedTextField();
        Cidade = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        avancar.setText("Salvar");
        avancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avancarActionPerformed(evt);
            }
        });

        JLabelNomeCompleto.setText("Nome Completo:");

        JLabelCPF.setText("CPF:");

        JLabelEmail.setText("E-mail:");

        JLabelTelefone.setText("Telefone:");

        JLabelSexo.setText("Sexo:");

        JLabelData.setText("Data de Nascimento:");

        JLabelEstadoCivil.setText("Estado Civíl:");

        try {
            Nome.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("**************************************************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeActionPerformed(evt);
            }
        });

        try {
            CPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            Email.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("*******************************************************************************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            Telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        SexoID.add(Masculino);
        Masculino.setText("Masculino");
        Masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasculinoActionPerformed(evt);
            }
        });

        SexoID.add(Feminino);
        Feminino.setText("Feminino");
        Feminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemininoActionPerformed(evt);
            }
        });

        SexoID.add(NaoInformar);
        NaoInformar.setText("Não informar");

        try {
            Data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        EstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Informar..", "Solteiro", "Casado", "Viúvo", "Divorciado" }));
        EstadoCivil.setToolTipText("");
        EstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoCivilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DadosBasicosLayout = new javax.swing.GroupLayout(DadosBasicos);
        DadosBasicos.setLayout(DadosBasicosLayout);
        DadosBasicosLayout.setHorizontalGroup(
            DadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DadosBasicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DadosBasicosLayout.createSequentialGroup()
                        .addGap(0, 453, Short.MAX_VALUE)
                        .addComponent(avancar))
                    .addGroup(DadosBasicosLayout.createSequentialGroup()
                        .addGroup(DadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DadosBasicosLayout.createSequentialGroup()
                                .addComponent(JLabelNomeCompleto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DadosBasicosLayout.createSequentialGroup()
                                .addGroup(DadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLabelTelefone)
                                    .addComponent(JLabelSexo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(DadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(DadosBasicosLayout.createSequentialGroup()
                                        .addComponent(Masculino)
                                        .addGap(18, 18, 18)
                                        .addComponent(Feminino)
                                        .addGap(18, 18, 18)
                                        .addComponent(NaoInformar))))
                            .addGroup(DadosBasicosLayout.createSequentialGroup()
                                .addComponent(JLabelData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Data, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DadosBasicosLayout.createSequentialGroup()
                                .addComponent(JLabelEstadoCivil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DadosBasicosLayout.createSequentialGroup()
                                    .addComponent(JLabelEmail)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Email))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DadosBasicosLayout.createSequentialGroup()
                                    .addComponent(JLabelCPF)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        DadosBasicosLayout.setVerticalGroup(
            DadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DadosBasicosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(DadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelNomeCompleto)
                    .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelCPF)
                    .addComponent(CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelEmail)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelTelefone)
                    .addComponent(Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelSexo)
                    .addComponent(Masculino)
                    .addComponent(Feminino)
                    .addComponent(NaoInformar))
                .addGap(18, 18, 18)
                .addGroup(DadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelData)
                    .addComponent(Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelEstadoCivil)
                    .addComponent(EstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(avancar)
                .addContainerGap())
        );

        Table.addTab("Dados Básicos", DadosBasicos);

        Concluir.setText("Concluir");
        Concluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConcluirActionPerformed(evt);
            }
        });

        JLabelCEP.setText("CEP:");

        JLabelEnderecos.setText("Endereço:");

        JLabelNumero.setText("Número:");

        JLabelComplemento.setText("Complemento:");

        JLabelBairro.setText("Bairro");

        JLabelCidade.setText("Cidade:");

        JLabelEstado.setText("Estado:");

        try {
            Cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Cep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CepActionPerformed(evt);
            }
        });

        try {
            Endereco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("******************************************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnderecoActionPerformed(evt);
            }
        });

        try {
            Numero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("****")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroActionPerformed(evt);
            }
        });

        try {
            Complemento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("*************************************************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            Estado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout EndereçoLayout = new javax.swing.GroupLayout(Endereço);
        Endereço.setLayout(EndereçoLayout);
        EndereçoLayout.setHorizontalGroup(
            EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EndereçoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Concluir)
                .addContainerGap())
            .addGroup(EndereçoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(EndereçoLayout.createSequentialGroup()
                            .addComponent(JLabelCEP)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Cep, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(EndereçoLayout.createSequentialGroup()
                            .addComponent(JLabelEnderecos)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Endereco))
                        .addGroup(EndereçoLayout.createSequentialGroup()
                            .addComponent(JLabelCidade)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(JLabelEstado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(EndereçoLayout.createSequentialGroup()
                            .addComponent(JLabelNumero)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(JLabelComplemento)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(EndereçoLayout.createSequentialGroup()
                        .addComponent(JLabelBairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 150, Short.MAX_VALUE))
        );
        EndereçoLayout.setVerticalGroup(
            EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EndereçoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelCEP)
                    .addComponent(Cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelEnderecos)
                    .addComponent(Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelNumero)
                    .addComponent(Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelComplemento)
                    .addComponent(Complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelBairro)
                    .addComponent(Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelCidade)
                    .addComponent(JLabelEstado)
                    .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addComponent(Concluir)
                .addContainerGap())
        );

        Table.addTab("Endereço", Endereço);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Table, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Table)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadoCivilActionPerformed
            public void limparDados1 (){
        Cep.setText("");
        Endereco.setText("");
        Numero.setText("");
        Complemento.setText("");
        Bairro.setText("");
        Cidade.setText("");
        Estado.setText("");
    }
    private void ConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConcluirActionPerformed
    validadorClientes validador2 = new validadorClientes();
        
    String CEP = Cep.getText();
    String Endereco1 = Endereco.getText();
    String Num = Numero.getText();
    String Compl = Complemento.getText();
    String Bairro1 = Bairro.getText();
    String Cidade1 = Cidade.getText();
    String Estado1 = Estado.getText();
    
    if(validador2.validarE(Cep, Endereco, Numero, Complemento, Bairro, Cidade, Estado)){
    Cliente dados2 = new Cliente();
    Controller.info2(CEP, Endereco1, Num, Compl, Bairro1, Cidade1, Estado1);
    //dados2.Info2(CEP, Endereco1, Num, Compl, Bairro1, Cidade1, Estado1);
    JOptionPane.showMessageDialog(null, "Cadastro Concluido!");
    limparDados1();
    }
        
        
    }//GEN-LAST:event_ConcluirActionPerformed

    private void NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeActionPerformed
      
    }//GEN-LAST:event_NomeActionPerformed

    private void CepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CepActionPerformed

    private void FemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemininoActionPerformed

    private void MasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MasculinoActionPerformed
            public void limparDados2 (){
        Nome.setText("");
        CPF.setText("");
        Email.setText("");
        Telefone.setText("");
        Data.setText("");
        EstadoCivil.setSelectedIndex(0);
    }
    private void avancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avancarActionPerformed
       validadorClientes validador = new validadorClientes();
       
        String nome = Nome.getText();
        String cpf = CPF.getText();
        String email = Email.getText();
        String telefone = Telefone.getText();
        String sexo = "";
        if(Masculino.isSelected()){sexo = "Masculino";}
        if(Feminino.isSelected()){sexo = "Feminino";}
        if(NaoInformar.isSelected()){sexo = "Não Informado";}
        String dataN = Data.getText();
        String estadoC = EstadoCivil.getSelectedItem().toString();
        
       if(validador.validarC(Nome, CPF, Email, Telefone, sexo, Data, EstadoCivil)){
       Cliente dados = new Cliente();
       Controller.salvarCliente(nome, cpf, email, telefone, sexo, dataN, estadoC);
       //dados.info(nome, cpf, email, telefone, sexo, dataN, estadoC);
       JOptionPane.showMessageDialog(null, "Dados salvos.");
       limparDados2();
    }
    }//GEN-LAST:event_avancarActionPerformed

    private void EnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnderecoActionPerformed

    private void NumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastrarClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Bairro;
    private javax.swing.JFormattedTextField CPF;
    private javax.swing.JFormattedTextField Cep;
    private javax.swing.JFormattedTextField Cidade;
    private javax.swing.JFormattedTextField Complemento;
    private javax.swing.JButton Concluir;
    private javax.swing.JPanel DadosBasicos;
    private javax.swing.JFormattedTextField Data;
    private javax.swing.JFormattedTextField Email;
    private javax.swing.JFormattedTextField Endereco;
    private javax.swing.JPanel Endereço;
    private javax.swing.JFormattedTextField Estado;
    private javax.swing.JComboBox<String> EstadoCivil;
    private javax.swing.JRadioButton Feminino;
    private javax.swing.JLabel JLabelBairro;
    private javax.swing.JLabel JLabelCEP;
    private javax.swing.JLabel JLabelCPF;
    private javax.swing.JLabel JLabelCidade;
    private javax.swing.JLabel JLabelComplemento;
    private javax.swing.JLabel JLabelData;
    private javax.swing.JLabel JLabelEmail;
    private javax.swing.JLabel JLabelEnderecos;
    private javax.swing.JLabel JLabelEstado;
    private javax.swing.JLabel JLabelEstadoCivil;
    private javax.swing.JLabel JLabelNomeCompleto;
    private javax.swing.JLabel JLabelNumero;
    private javax.swing.JLabel JLabelSexo;
    private javax.swing.JLabel JLabelTelefone;
    private javax.swing.JRadioButton Masculino;
    private javax.swing.JRadioButton NaoInformar;
    private javax.swing.JFormattedTextField Nome;
    private javax.swing.JFormattedTextField Numero;
    private javax.swing.ButtonGroup SexoID;
    private javax.swing.JTabbedPane Table;
    private javax.swing.JFormattedTextField Telefone;
    private javax.swing.JButton avancar;
    // End of variables declaration//GEN-END:variables

    }

